

test.o: test.c
	cc -I/opt/local/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -pipe -Os -arch x86_64 test.c
